all:
  hosts:
    node1:
      ansible_host: 10.0.10.101
      ip: 10.0.10.101
      access_ip: 10.0.10.101
    node2:
      ansible_host: 10.0.10.102
      ip: 10.0.10.102
      access_ip: 10.0.10.102
    node3:
      ansible_host: 10.0.10.103
      ip: 10.0.10.103
      access_ip: 10.0.10.103
    node4:
      ansible_host: 10.0.10.104
      ip: 10.0.10.104
      access_ip: 10.0.10.104
  children:
    kube_control_plane:
      hosts:
        node1:
    kube_node:
      hosts:
        node2:
        node3:
        node4:
    etcd:
      hosts:
        node1:
    k8s_cluster:
      children:
        kube_control_plane:
        kube_node:
    calico_rr:
      hosts: {}
